import { GoogleGenAI } from "@google/genai";
import fs from "node:fs";
import path from "node:path";

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GEMINI_API_KEY || process.env.GEMINI_API_KEY || "",
});

/**
 * Generate or edit an image using Gemini's "Nano Banana" capabilities
 */
export async function generateGeminiImage({
  productImageUrl,
  referenceImagePath,
  productName,
  view,
  background,
  additionalDetails,
  model = "gemini-2.5-flash-image",
}: {
  productImageUrl?: string;
  referenceImagePath?: string;
  productName: string;
  view: string;
  background: string;
  additionalDetails?: string;
  model?: string;
}): Promise<string> {
  const apiKey =
    process.env.GOOGLE_GEMINI_API_KEY || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error(
      "Gemini API key is not set (GOOGLE_GEMINI_API_KEY or GEMINI_API_KEY)"
    );
  }

  try {
    const promptText = `Create a professional e-commerce studio photograph. 
    ${
      referenceImagePath
        ? `The person from the reference image is wearing the ${
            productName || "clothing item"
          }.`
        : `Generate a professional model wearing the ${
            productName || "clothing item"
          }.`
    }
    
    Context:
    - Pose: ${view}
    - Setting: ${background}
    - Style: High-end commercial fashion photography
    ${additionalDetails ? `- Note: ${additionalDetails}` : ""}
    
    Technical Requirements:
    ${
      referenceImagePath
        ? "- Maintain the exact facial features and appearance of the person in the reference image."
        : ""
    }
    - The ${productName || "clothing item"} must be rendered with high fidelity.
    - Lighting should be consistent with a professional studio setup.`;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const contents: any[] = [{ text: promptText }];

    // 1. Add reference image if provided
    if (referenceImagePath) {
      const localRefPath = path.join(
        process.cwd(),
        "public",
        referenceImagePath
      );
      if (fs.existsSync(localRefPath)) {
        const refBuffer = fs.readFileSync(localRefPath);
        contents.push({
          inlineData: {
            mimeType: "image/jpeg",
            data: refBuffer.toString("base64"),
          },
        });
      }
    }

    // 2. Add product image if provided
    if (productImageUrl) {
      const productResponse = await fetch(productImageUrl);
      if (productResponse.ok) {
        const productBuffer = Buffer.from(await productResponse.arrayBuffer());
        contents.push({
          inlineData: {
            mimeType: "image/jpeg",
            data: productBuffer.toString("base64"),
          },
        });
      }
    }

    // 3. Generate content using the correct API for @google/genai
    const response = await ai.models.generateContent({
      model,
      contents,
    });

    // 4. Extract image from response
    const candidate = response.candidates?.[0];
    if (!candidate) throw new Error("No candidates returned from Gemini");

    if (!candidate.content || !candidate.content.parts) {
      throw new Error("No content or parts returned from Gemini candidate");
    }

    for (const part of candidate.content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image was generated by Gemini");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } catch (error: any) {
    console.error("Gemini Image Generation Error:", error);
    throw new Error(
      error.message || "Failed to generate image with Gemini. Please try again."
    );
  }
}

/**
 * Generate a clean e-commerce PRODUCT SHOT (product only, on a pure white
 * background) from an uploaded/existing image using Gemini.
 */
export async function generateGeminiProductShot({
  productImageUrl,
  productName,
  additionalDetails,
  model = "gemini-2.5-flash-image",
}: {
  productImageUrl: string;
  productName?: string;
  additionalDetails?: string;
  model?: string;
}): Promise<string> {
  const apiKey =
    process.env.GOOGLE_GEMINI_API_KEY || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error(
      "Gemini API key is not set (GOOGLE_GEMINI_API_KEY or GEMINI_API_KEY)"
    );
  }

  const promptText = `Create a professional e-commerce PRODUCT photograph of the ${
    productName || "product"
  } shown in the provided image.

Requirements:
- Use ONLY the product from the image — do not add a person, model, hands, mannequin, props or text.
- Place the product centered on a pure white (#FFFFFF) seamless studio background.
- Clean, even studio lighting with a soft, subtle shadow beneath the product.
- Sharp focus, high detail, true-to-life colours, product fills the frame nicely.
- Remove any background clutter from the original photo.
${additionalDetails ? `- Additional note: ${additionalDetails}` : ""}`;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const contents: any[] = [{ text: promptText }];

  const productResponse = await fetch(productImageUrl);
  if (!productResponse.ok) {
    throw new Error("Could not read the source image");
  }
  const productBuffer = Buffer.from(await productResponse.arrayBuffer());
  contents.push({
    inlineData: {
      mimeType: productResponse.headers.get("content-type") || "image/jpeg",
      data: productBuffer.toString("base64"),
    },
  });

  try {
    const response = await ai.models.generateContent({ model, contents });
    const candidate = response.candidates?.[0];
    const parts = candidate?.content?.parts;
    if (!parts) throw new Error("No image returned from Gemini");
    for (const part of parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image was generated by Gemini");
  } catch (error) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const e = error as any;
    console.error("Gemini Product Shot Error:", e);
    throw new Error(e?.message || "Failed to generate product shot.");
  }
}
