import OpenAI from "openai";
import fs from "fs";
import path from "path";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

/**
 * Generate a model shot using the product image and a reference model image
 * Uses GPT-Image model via Responses API for high-fidelity reference-based generation
 */
export async function generateModelShot({
  productImageUrl,
  referenceImagePath,
  productName,
  view,
  background,
  additionalDetails,
  model = "gpt-4.1",
}: {
  productImageUrl: string;
  referenceImagePath: string;
  productName: string;
  view: string;
  background: string;
  additionalDetails?: string;
  model?: string;
}): Promise<string> {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY environment variable is not set");
  }

  try {
    // 1. Fetch and encode product image
    const productResponse = await fetch(productImageUrl);
    if (!productResponse.ok) {
      throw new Error("Failed to fetch product image");
    }
    const productBuffer = Buffer.from(await productResponse.arrayBuffer());
    const productBase64 = productBuffer.toString("base64");

    // 2. Read and encode reference model image
    // referenceImagePath is like "/images/dark female.jpg"
    const localRefPath = path.join(process.cwd(), "public", referenceImagePath);
    if (!fs.existsSync(localRefPath)) {
      throw new Error(`Reference image not found at ${localRefPath}`);
    }
    const refBuffer = fs.readFileSync(localRefPath);
    const refBase64 = refBuffer.toString("base64");

    // 3. Build the prompt
    const safeProductName = productName || "clothing item";
    const prompt = `Create a professional e-commerce studio photograph. 
    The person from the first reference image is wearing the ${safeProductName} shown in the second reference image.
    
    Context:
    - Pose: ${view}
    - Setting: ${background}
    - Style: High-end commercial fashion photography
    ${additionalDetails ? `- Note: ${additionalDetails}` : ""}
    
    Technical Requirements:
    - Maintain the exact facial features and appearance of the person in the first reference image.
    - The ${safeProductName} must be rendered with high fidelity, matching the colors and details from the second reference image.
    - Ensure a clean, professional integration of the ${safeProductName} onto the person.
    - Lighting should be consistent with a professional studio setup.`;

    // 4. Call GPT-Image via Responses API
    // @ts-ignore - Responses API might not be in the types yet
    const response = await openai.responses.create({
      model: model,
      input: [
        {
          role: "user",
          content: [
            { type: "input_text", text: prompt },
            {
              type: "input_image",
              image_url: `data:image/jpeg;base64,${refBase64}`,
              detail: "high",
            },
            {
              type: "input_image",
              image_url: `data:image/jpeg;base64,${productBase64}`,
              detail: "high",
            },
          ],
        },
      ],
      tools: [{ type: "image_generation" }],
    });

    // 5. Extract generated image
    // @ts-ignore
    const imageData = response.output
      .filter((output: any) => output.type === "image_generation_call")
      .map((output: any) => output.result);

    if (imageData.length > 0) {
      return `data:image/png;base64,${imageData[0]}`;
    } else {
      // @ts-ignore
      console.error("GPT-Image Output:", response.output);
      throw new Error("No image generated by GPT-Image");
    }
  } catch (error: unknown) {
    console.error("GPT-Image Generation Error:", error);
    throw new Error(
      error instanceof Error
        ? error.message
        : "Failed to generate image. Please try again."
    );
  }
}

/**
 * Legacy function for backwards compatibility - analyzes product image
 */
export async function analyzeProductImage(imageUrl: string): Promise<string> {
  if (!process.env.OPENAI_API_KEY) {
    console.warn("OPENAI_API_KEY not set, skipping image analysis");
    return "";
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        {
          role: "system",
          content: `You are a fashion product analyst. Describe products in extreme detail for image generation.`,
        },
        {
          role: "user",
          content: [
            {
              type: "text",
              text: `Describe this cap/hat in detail: style, colors, materials, logos, and design elements. Keep it concise (2-3 sentences).`,
            },
            {
              type: "image_url",
              image_url: {
                url: imageUrl,
                detail: "high",
              },
            },
          ],
        },
      ],
      max_tokens: 200,
    });

    return response.choices[0]?.message?.content || "";
  } catch (error) {
    console.error("OpenAI Vision Analysis Error:", error);
    return "";
  }
}

/**
 * Legacy function - simple text-to-image generation with DALL-E 3
 */
export async function generateProductImage(prompt: string): Promise<string> {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY environment variable is not set");
  }

  try {
    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt,
      n: 1,
      size: "1024x1024",
      quality: "hd",
      style: "natural",
      response_format: "url",
    });

    const imageUrl = response.data?.[0]?.url;
    if (!imageUrl) {
      throw new Error("No image generated");
    }

    return imageUrl;
  } catch (error: unknown) {
    console.error("OpenAI Image Generation Error:", error);
    throw new Error("Failed to generate image. Please try again.");
  }
}

export { openai };
